/*
 * ultrasonic.h
 *
 *  Created on: 24 May 2024
 *      Author: ahmed
 */

#ifndef SRC_ULTRASONIC_H_
#define SRC_ULTRASONIC_H_

#include "std_types.h"
#include"icu.h"
#include"gpio.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define ULTRASONIC_TRIGGER_PORT 					PORTD_ID
#define ULTRASONIC_TRIGGER_PIN  					PIN4_ID

/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/
/* Setup the ICU call back function.
 * Initialize the ICU driver as required.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 * */
void Ultrasonic_init(void);

/* Send the Trigger pulse to the ultrasonic for 10 microsecond*/
void Ultrasonic_Trigger(void);

/* Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance(void);


/* This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* SRC_ULTRASONIC_H_ */
